### ISSUE TITLE
Document how to use bootloader

### ISSUE THREAD

**Issue by xobs** [tinyfpga/TinyFPGA-Bootloader#59]
While the protocol is well-documented, there is no documentation on how to use it.

In the `programmer` directory it says to run `tinyprog -l`, however it doesn't say how to use tinyprog.

There is a `setup.py`, however it doesn't work:

```powershell
❯ python .\setup.py
Traceback (most recent call last):
File ".\setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
```

There is a directory called `tinyprog`, and surprisingly Python seems to recognize this, however it doesn't work either:

```
❯ python tinyprog
Traceback (most recent call last):
File "D:\obj\Windows-Release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\Windows-Release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "tinyprog\__main__.py", line 10, in <module>
    from six.moves.urllib.request import urlopen
ModuleNotFoundError: No module named 'six'
```

**Comment by marcan** [comment]
It's telling you you don't have `setuptools` installed. `setuptools` is required to run `setup.py` for many, if not the majority, of `setup.py` scripts out there.

This is all completely standard fare for installing Python packages, it shouldn't be particularly surprising or hard to figure out.
